(() => {
'use strict';
const SAVE='cozy-shelter-prototype-v1', GRID=15;
const R={power:['⚡','Power'],water:['💧','Water'],crops:['🌱','Crops'],meals:['🍲','Meals'],med:['🩺','Health pts'],info:['📻','Info'],tech:['🔬','Upgrade pts'],parts:['🔧','Parts']};
const order=Object.keys(R);
const ROOMS={
 single_bedroom:['Single Bedroom','One settler sleeps here at a time. Sleep restores energy fastest and gently repairs health.'],
 dining_room:['Dining Room','The cook turns crops + water into meals. Eating restores hunger and a little energy.'],
 power_generator:['Power Generator','Produces power. When power runs out, rooms switch to their lights-off art and work slows down.'],
 medical_room:['Medical Room','Produces health points. Sick or hurt settlers spend them to recover; otherwise they simply rest and work less.'],
 water_extractor:['Water Extractor','Draws water from underground. Water handles thirst, cooking, and showers.'],
 underground_garden:['Underground Garden','Produces crop points for the cook.'],
 washroom:['Washroom','Low-hygiene settlers shower automatically. Showering uses water, restores hygiene, and helps keep health steady.'],
 arcade_room:['Arcade Room','Settlers recharge a little energy and a lot of happiness here while waiting for a free bed.'],
 science_lab:['Science Lab','Consumes Info and produces Upgrade Points used to improve rooms.'],
 gym:['Gym','Training raises stamina/max energy, but it is tiring.'],
 radio_room:['Radio Room','Produces Info Points for the Science Lab.']
};
const defs=[
 [1,'Gardener','Gardening & Food Production','underground_garden','garden_work'],
 [2,'Power Technician','Power Systems','power_generator','repair_generator'],
 [3,'Engineer','Maintenance & Parts','power_generator','repair_machine'],
 [4,'Water Technician','Water Systems','water_extractor','operate_valve'],
 [5,'Nurse','Medical Care','medical_room','medical_kit'],
 [6,'Fitness Trainer','Stamina Training','gym','lift_weight'],
 [7,'Sanitation Specialist','Hygiene & Sanitation','washroom','clean_spill'],
 [8,'Chef','Cooking','dining_room','cook_pot'],
 [9,'Radio Operator','Communications','radio_room','operate_radio_console'],
 [10,'Scientist','Science & Research','science_lab','analyze_tablet']
];
const startRooms=['single_bedroom','dining_room','power_generator','water_extractor','underground_garden','medical_room','washroom','arcade_room','gym','radio_room','science_lab',null,null,null,null];
let S,sel={kind:null,id:null},last=performance.now(),acc=0; const E={};
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n)),cap=n=>clamp(n,0,999),fmt=n=>n>=100?Math.floor(n):n.toFixed(1);
function initial(){
 return {version:1,speed:1,simTime:0,resources:{power:65,water:70,crops:55,meals:22,med:7,info:0,tech:8,parts:48},rooms:startRooms.map((t,i)=>t?{type:t,slot:i,level:1}:null),settlers:defs.map((d,i)=>({id:d[0],role:d[1],specialty:d[2],jobRoom:d[3],jobPose:d[4],name:`Settler ${String(d[0]).padStart(2,'0')}`,energy:46+(i*7)%37,maxEnergy:100,hunger:62+(i*5)%27,thirst:66+(i*8)%25,health:100,hygiene:58+(i*6)%34,happiness:72,staminaLevel:1,sick:false,hurt:false,action:'work',actionUntil:0,locationSlot:null,reservedSlot:null})),log:[{t:0,text:'All ten settlers reached the shelter together. The old house above is quiet; the bunker below is home now.'},{t:0,text:'There is only one bedroom. The tiredest settler gets the bed first; everyone else can wait or recharge in the arcade.'}],savedAt:Date.now()};
}
function init(){
 ['world','bunkerGrid','settlerLayer','resources','roster','detailContent','eventLog','dayNumber','clockText'].forEach(id=>E[id]=document.getElementById(id));
 try{S=JSON.parse(localStorage.getItem(SAVE))||initial()}catch{S=initial()}
 if(S.version!==1)S=initial(); shape(); offline(); assign(true); buildGrid(); buildSprites(); bind(); render(); requestAnimationFrame(loop); setInterval(save,5000); addEventListener('resize',position);
}
function shape(){S.rooms=Array.from({length:GRID},(_,i)=>S.rooms?.[i]??null); S.resources.tech??=0;S.resources.parts??=0;S.settlers.forEach((s,i)=>{let d=defs[i];Object.assign(s,{role:d[1],specialty:d[2],jobRoom:d[3],jobPose:d[4]});s.staminaLevel??=1;s.sick??=false;s.hurt??=false;s.reservedSlot??=null;});}
function save(){S.savedAt=Date.now();try{localStorage.setItem(SAVE,JSON.stringify(S))}catch{}}
function offline(){let sec=Math.min(Math.max(0,(Date.now()-(S.savedAt||Date.now()))/1000),14400);if(sec<20)return;let g=sec*.2;S.resources.power=cap(S.resources.power+g*.20);S.resources.water=cap(S.resources.water+g*.18);S.resources.crops=cap(S.resources.crops+g*.14);S.resources.parts=cap(S.resources.parts+g*.025);S.resources.med=cap(S.resources.med+g*.018);S.resources.info=cap(S.resources.info+g*.016);let c=Math.min(S.resources.crops/1.5,S.resources.water/.8,g*.04);S.resources.crops-=c*1.5;S.resources.water-=c*.8;S.resources.meals=cap(S.resources.meals+c);log(`While you were away, the shelter quietly kept working. Offline progress only helps; needs do not worsen while the game is closed.`)}
function buildGrid(){E.bunkerGrid.innerHTML='';for(let slot=0;slot<GRID;slot++){let r=S.rooms[slot],el=document.createElement('div');el.className=`slot ${r?r.type:'empty-slot'}`;el.dataset.slot=slot;if(r)el.innerHTML=`<img class="room-art" alt="${ROOMS[r.type][0]}"><span class="room-level">${r.level}</span><span class="room-name">${ROOMS[r.type][0]}</span>`;el.onclick=()=>selectRoom(slot);E.bunkerGrid.appendChild(el)}roomArt()}
function buildSprites(){E.settlerLayer.innerHTML='';S.settlers.forEach(s=>{let i=document.createElement('img');i.className='settler-sprite';i.dataset.id=s.id;i.alt=s.name;i.onclick=e=>{e.stopPropagation();selectSettler(s.id)};E.settlerLayer.appendChild(i)})}
function bind(){document.querySelectorAll('.speed').forEach(b=>{b.classList.toggle('active',+b.dataset.speed===S.speed);b.onclick=()=>{S.speed=+b.dataset.speed;document.querySelectorAll('.speed').forEach(x=>x.classList.toggle('active',x===b))}});document.getElementById('resetGame').onclick=()=>{if(confirm('Reset this prototype and start again with the original ten settlers?')){localStorage.removeItem(SAVE);S=initial();sel={kind:null,id:null};assign(true);buildGrid();buildSprites();render()}}}
function loop(now){let dt=Math.min((now-last)/1000,.5);last=now;S.simTime+=dt*S.speed;simulate(dt*S.speed);acc+=dt;if(acc>.25){acc=0;render()}requestAnimationFrame(loop)}
function simulate(dt){let powered=S.resources.power>.05,drain=S.rooms.filter(Boolean).reduce((a,r)=>a+.035*r.level,0);S.resources.power=Math.max(0,S.resources.power-drain*dt);
 for(const s of S.settlers){if(s.action==='work'){s.energy-=.09*dt;s.hunger-=.025*dt;s.thirst-=.034*dt;s.hygiene-=.020*(working(7)?.72:1)*dt}else if(s.action==='sleep'){s.energy+=2.35*mult(S.rooms[s.reservedSlot])*dt;s.health+=.24*dt;s.hunger-=.008*dt;s.thirst-=.01*dt}else if(s.action==='arcade'){s.energy+=.72*dt;s.happiness+=1.55*dt;s.hunger-=.012*dt;s.thirst-=.016*dt}else if(s.action==='training'){s.energy-=1.15*dt;s.thirst-=.08*dt}else{s.energy-=.018*dt;s.hunger-=.014*dt;s.thirst-=.02*dt;s.hygiene-=.008*dt}if(s.hygiene<25)s.health-=.018*dt;if(s.hunger<12)s.health-=.012*dt;if(s.thirst<12)s.health-=.022*dt;if(s.energy<8)s.health-=.010*dt;if(s.sick)s.health-=.008*dt;s.energy=clamp(s.energy,0,s.maxEnergy);['hunger','thirst','health','hygiene','happiness'].forEach(k=>s[k]=clamp(s[k],k==='health'?15:0,100));if(s.action!=='work'&&s.actionUntil&&S.simTime>=s.actionUntil)finish(s)}
 for(const s of S.settlers){if(s.action!=='work')continue;let rm=find(s.jobRoom),eff=efficiency(s)*mult(rm)*(powered||s.id===2||s.id===3?1:.28);if(eff<=0)continue;if(s.id===1)S.resources.crops+=.31*eff*dt;if(s.id===2)S.resources.power+=.70*eff*dt;if(s.id===3)S.resources.parts+=.060*eff*dt;if(s.id===4)S.resources.water+=.43*eff*dt;if(s.id===5)S.resources.med+=.052*eff*dt;if(s.id===8){let a=Math.min(.115*eff*dt,S.resources.crops/1.5,S.resources.water/.8);S.resources.crops-=a*1.5;S.resources.water-=a*.8;S.resources.meals+=a}if(s.id===9)S.resources.info+=.060*eff*dt;if(s.id===10){let a=Math.min(.046*eff*dt,S.resources.info);S.resources.info-=a;S.resources.tech+=a*.72}}
 order.forEach(k=>S.resources[k]=cap(S.resources[k]));
 for(const s of S.settlers){if(s.action==='work'&&!s.hurt&&Math.random()<.000018*dt){s.hurt=true;s.health=Math.max(35,s.health-18);log(`${s.name} got a minor work injury. They cannot die from it; treatment or rest will get them back on their feet.`)}if(!s.sick&&s.hygiene<28&&Math.random()<.00003*dt){s.sick=true;s.health=Math.max(35,s.health-10);log(`${s.name} feels under the weather. A shower helps prevention, and the medical room can treat them.`)}}
 S.settlers.filter(s=>s.action==='work').forEach(choose);
}
function choose(s){if((s.sick||s.hurt||s.health<55)&&S.resources.med>=4&&capacity('medical_room',2)){S.resources.med-=4;start(s,'medical','medical_room',9,'sick');return}if(s.hygiene<34&&S.resources.water>=2&&capacity('washroom',2)){S.resources.water-=2;start(s,'shower','washroom',8,'happy');return}if(s.hunger<38&&S.resources.meals>=1&&capacity('dining_room',3)){S.resources.meals-=1;start(s,'eat','dining_room',5,'eat');return}if(s.thirst<34&&S.resources.water>=.5){S.resources.water-=.5;s.thirst=clamp(s.thirst+42,0,100);s.energy=clamp(s.energy+2,0,s.maxEnergy);return}if(s.energy<31||s.health<45||((s.sick||s.hurt)&&S.resources.med<4)){let b=freeBed();if(b){sleep(s,b.slot);return}if(capacity('arcade_room',3)){start(s,'arcade','arcade_room',11,'happy');return}}if(s.happiness<42&&capacity('arcade_room',3))start(s,'arcade','arcade_room',10,'happy')}
function start(s,a,t,d,p){let r=find(t);if(!r)return;s.action=a;s.actionUntil=S.simTime+d;s.locationSlot=r.slot;s.reservedSlot=r.slot;s.actionPose=p;move(s)}
function sleep(s,slot){s.action='sleep';s.actionUntil=S.simTime+30;s.locationSlot=slot;s.reservedSlot=slot;s.actionPose='tired';log(`${s.name} got the bed and pulled the privacy curtain closed.`);move(s);roomArt()}
function finish(s){let a=s.action;if(a==='sleep'){s.energy=Math.max(s.energy,s.maxEnergy*.90);s.health=clamp(s.health+4,15,100)}if(a==='eat'){s.hunger=clamp(s.hunger+40,0,100);s.energy=clamp(s.energy+9,0,s.maxEnergy);s.happiness=clamp(s.happiness+2,0,100)}if(a==='shower'){s.hygiene=clamp(s.hygiene+62,0,100);s.health=clamp(s.health+5,15,100);s.happiness=clamp(s.happiness+4,0,100)}if(a==='medical'){s.health=clamp(s.health+42,15,100);s.sick=false;s.hurt=false;log(`${s.name} finished treatment and is feeling much better.`)}if(a==='training'){s.maxEnergy+=working(6)?4.5:3;s.staminaLevel++;s.happiness=clamp(s.happiness+3,0,100);log(`${s.name} finished stamina training. Max energy is now ${Math.round(s.maxEnergy)}.`)}s.action='work';s.actionUntil=0;s.reservedSlot=null;s.locationSlot=jobSlot(s);s.actionPose=s.jobPose;move(s);roomArt()}
function assign(){S.settlers.forEach(s=>{if(!s.action||s.action==='work'){s.action='work';s.locationSlot=jobSlot(s);s.actionPose=s.jobPose}})}
const find=t=>S.rooms.find(r=>r?.type===t)||null, mult=r=>1+((r?.level||1)-1)*.22,working=id=>S.settlers.find(s=>s.id===id)?.action==='work';
function jobSlot(s){return find(s.jobRoom)?.slot??0}function freeBed(){let beds=S.rooms.filter(r=>r?.type==='single_bedroom');return beds.find(b=>!S.settlers.some(s=>s.action==='sleep'&&s.reservedSlot===b.slot))||null}function capacity(t,n){let r=find(t);return !!r&&S.settlers.filter(s=>s.action!=='work'&&s.locationSlot===r.slot).length<n}
function efficiency(s){let e=1;if(s.energy<25)e*=.55;if(s.hunger<25)e*=.65;if(s.thirst<25)e*=.60;if(s.hygiene<25)e*=.80;if(s.health<60)e*=.65;if(s.sick||s.hurt)e*=.50;return e}
function buildBed(slot){if(S.rooms[slot])return;let c=S.rooms.filter(r=>r?.type==='single_bedroom').length,cost=30+Math.max(0,c-1)*8;if(S.resources.parts<cost){log(`Another bedroom needs ${cost} Parts. The engineer will keep making more.`);return}S.resources.parts-=cost;S.rooms[slot]={type:'single_bedroom',slot,level:1};log('A new private bedroom was excavated. One more settler can now sleep at the same time.');buildGrid();selectRoom(slot)}
function upgrade(slot){let r=S.rooms[slot];if(!r||r.level>=5)return;let tc=8+(r.level-1)*6,pc=10+(r.level-1)*8;if(S.resources.tech<tc||S.resources.parts<pc){log(`Upgrade needs ${tc} Upgrade Points and ${pc} Parts.`);return}S.resources.tech-=tc;S.resources.parts-=pc;r.level++;log(`${ROOMS[r.type][0]} upgraded to level ${r.level}.`);buildGrid();selectRoom(slot)}
function train(){let s=S.settlers.filter(x=>x.action==='work'&&x.energy>55&&x.id!==6).sort((a,b)=>a.maxEnergy-b.maxEnergy||a.energy-b.energy)[0];if(!s){log('Nobody is rested enough to train right now.');return}start(s,'training','gym',12,'happy');log(`${s.name} started stamina training.`)}
function selectRoom(id){sel={kind:S.rooms[id]?'room':'empty',id};selection();marks()}function selectSettler(id){sel={kind:'settler',id};selection();marks()}
function render(){resources();roomArt();roster();sprites();position();clock();logs();selection();marks()}
function resources(){E.resources.innerHTML=order.map(k=>`<div class="resource-pill"><span class="icon">${R[k][0]}</span><b>${fmt(S.resources[k])}</b><small>${R[k][1]}</small></div>`).join('')}
function roomArt(){let power=S.resources.power>.05;document.querySelectorAll('.slot').forEach(el=>{let slot=+el.dataset.slot,r=S.rooms[slot];if(!r)return;let sleeper=r.type==='single_bedroom'&&S.settlers.some(s=>s.action==='sleep'&&s.reservedSlot===slot),v=sleeper?'sleep':power?'lights_on':'lights_off',img=el.querySelector('.room-art');if(img&&img.getAttribute('src')!==`rooms/${r.type}/${v}.png`)img.src=`rooms/${r.type}/${v}.png`;let b=el.querySelector('.room-level');if(b)b.textContent=r.level})}
function roster(){E.roster.innerHTML=S.settlers.map(s=>`<div class="roster-card" data-id="${s.id}"><img src="${path(s,face(s))}"><div><b>${s.name}</b><small>${status(s)}</small><div class="mini-bar"><span style="width:${Math.round(s.energy/s.maxEnergy*100)}%"></span></div></div></div>`).join('');E.roster.querySelectorAll('.roster-card').forEach(c=>c.onclick=()=>selectSettler(+c.dataset.id))}
function sprites(){S.settlers.forEach(s=>{let i=E.settlerLayer.querySelector(`[data-id="${s.id}"]`);if(!i)return;i.classList.toggle('sleeping',s.action==='sleep');if(i.dataset.moving==='1')return;let src=path(s,pose(s));if(i.getAttribute('src')!==src)i.src=src;i.title=`${s.name} — ${s.role} — ${status(s)}`})}
function move(s){let i=E.settlerLayer.querySelector(`[data-id="${s.id}"]`);if(!i)return;i.classList.remove('sleeping');i.dataset.moving='1';i.src=path(s,'walk_01');position();let f=1,iv=setInterval(()=>{f=f===1?2:1;i.src=path(s,`walk_0${f}`)},220);setTimeout(()=>{clearInterval(iv);i.dataset.moving='0';if(s.action==='sleep')i.classList.add('sleeping');i.src=path(s,pose(s))},820)}
function position(){let w=E.world.getBoundingClientRect(),groups=new Map;S.settlers.forEach(s=>{let slot=Number.isInteger(s.locationSlot)?s.locationSlot:jobSlot(s);if(!groups.has(slot))groups.set(slot,[]);groups.get(slot).push(s)});for(let [slot,g] of groups){let cell=E.bunkerGrid.querySelector(`[data-slot="${slot}"]`);if(!cell)continue;let r=cell.getBoundingClientRect();g.forEach((s,n)=>{let i=E.settlerLayer.querySelector(`[data-id="${s.id}"]`),space=Math.min(r.width*.18,24),off=(n-(g.length-1)/2)*space,left=r.left-w.left+r.width*.5+off,top=r.top-w.top+r.height*.84;i.style.left=`${left/w.width*100}%`;i.style.top=`${top/w.height*100}%`})}}
function selection(){if(!sel.kind)return;if(sel.kind==='settler'){let s=S.settlers.find(x=>x.id===sel.id);E.detailContent.innerHTML=`<h2>${s.name}</h2><p>${s.specialty}</p><span class="badge">${status(s)} · Stamina Lv. ${s.staminaLevel}</span><div class="detail-grid">${meter('⚡ Energy',s.energy,s.maxEnergy,'energy')}${meter('❤️ Health',s.health,100,'health')}${meter('🍲 Fullness',s.hunger,100,'hunger')}${meter('💧 Hydration',s.thirst,100,'thirst')}${meter('🚿 Hygiene',s.hygiene,100,'hygiene')}${meter('😊 Happiness',s.happiness,100,'happiness')}</div><div class="tip-card"><b>No permadeath</b><span>If health gets low, ${s.name} pauses or works with a debuff. Sleep, showers, meals, water, and medical treatment bring them back.</span></div>`;return}let slot=sel.id,r=S.rooms[slot];if(!r){let count=S.rooms.filter(x=>x?.type==='single_bedroom').length,cost=30+Math.max(0,count-1)*8;E.detailContent.innerHTML=`<h2>Empty excavation square</h2><p>This space can become another one-person sleeping quarter.</p><div class="tip-card"><b>Why more bedrooms?</b><span>Only one settler can sleep behind a bedroom curtain at a time.</span></div><div class="action-row"><button class="action-btn primary" id="buildBedroom" ${S.resources.parts<cost?'disabled':''}>Build Bedroom · ${cost} 🔧</button></div>`;document.getElementById('buildBedroom')?.addEventListener('click',()=>buildBed(slot));return}let tc=8+(r.level-1)*6,pc=10+(r.level-1)*8;E.detailContent.innerHTML=`<h2>${ROOMS[r.type][0]}</h2><p>${ROOMS[r.type][1]}</p><span class="badge">Level ${r.level} · ${Math.round((mult(r)-1)*100)}% bonus</span><div class="action-row"><button class="action-btn primary" id="upgradeRoom" ${(r.level>=5||S.resources.tech<tc||S.resources.parts<pc)?'disabled':''}>Upgrade · ${tc} 🔬 + ${pc} 🔧</button>${r.type==='gym'?'<button class="action-btn" id="trainStamina">Train lowest stamina</button>':''}</div>`;document.getElementById('upgradeRoom')?.addEventListener('click',()=>upgrade(slot));document.getElementById('trainStamina')?.addEventListener('click',train)}
function marks(){document.querySelectorAll('.slot').forEach(e=>e.classList.toggle('selected',sel.kind!=='settler'&&+e.dataset.slot===sel.id));document.querySelectorAll('.settler-sprite,.roster-card').forEach(e=>e.classList.toggle('selected',sel.kind==='settler'&&+e.dataset.id===sel.id))}
function clock(){let m=8*60+Math.floor(S.simTime*5);E.dayNumber.textContent=1+Math.floor(m/1440);m%=1440;E.clockText.textContent=`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
function logs(){E.eventLog.innerHTML=S.log.slice(-12).reverse().map(e=>`<div class="log-entry"><time>${lt(e.t)}</time>${e.text}</div>`).join('')}function log(text){S.log.push({t:S.simTime,text});if(S.log.length>80)S.log.splice(0,S.log.length-80)}
function pose(s){if(s.action==='work')return s.jobPose;if(s.action==='eat')return'eat';if(s.action==='medical')return'sick';if(['shower','arcade','training'].includes(s.action))return'happy';if(s.sick)return'sick';if(s.hunger<30)return'hungry';if(s.energy<30)return'tired';if(s.health<55)return'sad';return'idle'}
function face(s){if(s.sick)return'sick';if(s.hunger<28)return'hungry';if(s.energy<28)return'tired';if(s.health<55||s.happiness<40)return'sad';if(s.happiness>80)return'happy';return'idle'}
const path=(s,p)=>`settler_${String(s.id).padStart(2,'0')}/${p}.png`;
function status(s){return {work:`Working · ${s.role}`,sleep:'Sleeping',eat:'Eating a meal',shower:'Showering',medical:'Getting treatment',arcade:'Relaxing in the arcade',training:'Stamina training'}[s.action]||'Resting'}
function meter(l,v,max,c){return `<div class="stat-box"><label><span>${l}</span><b>${Math.round(v)}/${Math.round(max)}</b></label><div class="meter ${c}"><span style="width:${clamp(v/max*100,0,100)}%"></span></div></div>`}
function lt(t){let m=(8*60+Math.floor(t*5))%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`}
document.addEventListener('DOMContentLoaded',init);
})();
